### ISSUE TITLE
sout можно только в main

### ISSUE THREAD

**Issue by coursar** [Anvarmag/BMI#1]
https://github.com/Anvarmag/BMI/blob/39c063413204cecee162bfa2010ef09aa441b353/src/main/java/BmiService.java#L5-L9

**Comment by Anvarmag** [comment]
Убрал лишнее, так как не знаю как присвоить имя, а не число.

**Comment by Anvarmag** [comment]
Убрал лишнее, не знаю(пока) как присвоить имя, а не число.
